name: Deploy Periodic Table

on:
  push:
    branches: [ "main" ] # Or your main branch name
  pull_request:
    branches: [ "main" ]

permissions:
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust project
        run: cargo build --release
        working-directory: /home/runner/work/periodic-table/periodic-table

      - name: Generate index.html
        run: ./target/release/periodic-table # Ensure this matches your built executable name
        working-directory: /home/runner/work/periodic-table/periodic-table

      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: periodic-table
          path: /home/runner/work/periodic-table/periodic-table/index.html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: periodic-table # Update the artifact name here as well
