name: Generate and Commit Periodic Table

on:
  push:
    branches: [ "main" ] # Or your main branch name
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write # Required to commit and push changes

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust project
        run: cargo build --release
        working-directory: /home/runner/work/periodic-table/periodic-table

      - name: Generate index.html
        run: ./target/release/periodic-table # Ensure this matches your built executable name
        working-directory: /home/runner/work/periodic-table/periodic-table

      - name: Commit and push index.html to main
        run: |
          cd /home/runner/work/periodic-table/periodic-table
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions Bot"
          git add index.html
          git commit -m "Generate and update index.html" || echo "No changes to commit"
          git push origin main
          
