name: Deploy Periodic Table

on:
  push:
    branches: [ "main" ] # Or your main branch name
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Rust project
        run: cargo build --release
        working-directory: . # This line ensures the command runs in the root of your repository

      - name: Generate index.html
        run: ./
        working-directory: . # It's a good practice to specify the working directory here as well

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deploy_branch: gh-pages # Or your desired deployment branch
          folder: .        # The index.html is generated in the root
